---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
            args: [--allow-multiple-documents]
            files: ^kubernetes/.*.yaml$
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.28.0
      hooks:
          - id: yamllint
            files: ^kubernetes/.*.yaml$

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
            files: ^kubernetes/.*.yaml$

    - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate
      rev: v0.1.0
      hooks:
          - id: k8svalidate
            args: [--exclude, '**/*.patch.yaml']
            files: ^kubernetes/.*.yaml$

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
          - id: detect-secrets
            args: [--exclude-files, ^kubernetes/.*\.sops.yaml$]
