apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-release
  namespace: traefik
spec:
  interval: 1m
  chart:
    install:
      crds: skip
    spec:
      chart: traefik
      sourceRef:
        kind: GitRepository
        name: traefik-helm-chart
      interval: 1m
  values:
    hub:
      enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
