---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
labels:
  pod-security.kubernetes.io/enforce: privileged
  pod-security.kubernetes.io/audit: privileged
  pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: v0.13.7
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: metallb
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.35.1-192.168.35.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-l2adver
  namespace: metallb-system

