---
apiVersion: v1
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:MKEVT84K561fswUeOHSWL2KY2awSWp8Zm8juUdMu4S1zeDmMUXGLw3xshk0MvvAuQo+rXMO1q1U=,iv:jbS9tnD6ztms+WMFIE+S+OmAtgdgkCYipkNqoWLgDF8=,tag:IrMWg3trNQZhopZguA9fww==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:NB7TzJICjzazzbjj14i0vONf9Tav1QXchPDnKxgONt4lh40xzY2hLUGVVOZnThPhUyg5n2Yt9ig=,iv:PxrTkbbDhCNrBr6kaVxMAzmFcXHLniO/UVqqnA90JSs=,tag:6EbgN6J+ELvvxVgnB/icVg==,type:str]
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovatebot
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ppqa2hrsne3rx98pralkat0er96x90q336tx4xqtt2wqnqc9cccqcdclhq
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYXZjTXdSMVN2ZXA0RVRp
              bS9ZSC9TbWt6L21JQlVoYk9LL3BpdDFVUzNRCkxyWFBEeEQ2YkZLYjB3UEVyQm1M
              dXJ2aVhyQzBxU0JtRnY1bTBIUjZJTWMKLS0tIHVLTUlBSUFwZlBpSWM0MCt4U1px
              WnpXdlN2aUVFUUU3eXpxRjZEZk1jUTQKFnEwtFDwZMw4VAVY/ogpvYZyuUBjmd1C
              D7pc1mi4EALkdIMVz/r4Xfl8kfFtfNvUvggyT1xEXFjdX7aLHA2NJA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: '2022-11-04T05:54:59Z'
    mac: ENC[AES256_GCM,data:XgkiTjScUKCNgp9ALRoGdEWYVnG51wYn3jgltn6ug5slGD8hpNHe9hta7iMUxXgEPIMXJZTSVMUMnHCYs/kwm888opHHMaiNwbhFlQOEycuc8SVzqErOjwkI070eO508LJLg1P1AegKuya2626HmHaNVC8DFwQmuNgQayNlBBGU=,iv:cAMcSabNR666ac2hRt0OB5ZJf342s+RMNcJqf3dSGiE=,tag:c/jsJnxMyPt0vM4Gj1YugQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
