---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: metallb
    namespace: metallb-system
spec:
    interval: 1m
    ref:
        commit: 4b41fd5
    url: https://github.com/metallb/metallb.git
    ignore: |
        # exclude all
        /*
        # path to manifests
        !/config/
