apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cores
  namespace: flux-system
spec: 
  dependsOn:
    - name: sources
    - name: namespaces
    - name: crds
  interval: 1m
  path: ./kubernetes/cores
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-root-cluster
