apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: metallb
      version: v0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb

