- hosts: masters
  name: configure k3s master
  tasks:
    - name: create the k3s folder in etc rancher
      file:
        path: /etc/rancher/k3s
        state: directory
    - name: copy k3s configueration
      template:
        src: ../files/k3s-master-config.yaml
        dest: /etc/rancher/k3s/config.yaml
    - name: change the k3s.service.env file
      blockinfile:
        create: true
        path: /etc/systemd/system/k3s.service.env
        marker: "# {mark} k3s master config"
        block: |
          CMD_K3S_EXEC=server
    - name: start k3s master
      systemd:
        name: k3s
        state: restarted
        daemon_reload: true
    - name: copy kube config file
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../k3s-kube-config.yaml
        flat: true
- hosts: workers
  name: configure k3s worker
  tasks:
    - name: create the k3s folder in etc rancher
      file:
        path: /etc/rancher/k3s
        state: directory
    - name: copy k3s configueration
      template:
        src: ../files/k3s-worker-config.yaml
        dest: /etc/rancher/k3s/config.yaml
    - name: change the k3s.service.env file
      blockinfile:
        create: true
        path: /etc/systemd/system/k3s.service.env
        marker: "# {mark} k3s worker config"
        block: |
          CMD_K3S_EXEC=agent
    - name: start k3s workers
      systemd:
        name: k3s
        state: restarted
        daemon_reload: true
