---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: adguard-external-dns
    namespace: dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: adguard-external-dns-readonly-ingress
    namespace: dns
    annotations:
        rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
    - apiGroups:
          - extensions
      resources: ['*']
      verbs:
          - get
          - list
          - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: adguard-external-dns-role-binding
subjects:
    - kind: ServiceAccount
      name: adguard-external-dns
      namespace: dns
roleRef:
    kind: ClusterRole
    name: adguard-external-dns-readonly-ingress
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: adguard-external-dns
    namespace: dns
    labels:
        app: adguard-external-dns
spec:
    replicas: 1
    selector:
        matchLabels:
            app: adguard-external-dns
    template:
        metadata:
            labels:
                app: adguard-external-dns
        spec:
            serviceAccountName: adguard-external-dns
            containers:
                - name: adguard-external-dns
                  image: ghcr.io/5cat/adguard-external-dns:master  # yamllint disable-line
                  env:
                      - name: DOMAIN_NAME
                        value: heaven.ist
                      - name: ADGURED_HOST
                        value: adguard-adguard-home.dns.svc.cluster.local.:3000
