---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: adguard
    namespace: tests
spec:
    interval: 1m
    chart:
        spec:
            chart: adguard-home
            version: 5.5.2
            sourceRef:
                kind: HelmRepository
                name: k8s-at-home
    values:
        service:
            dns-tcp:
                enabled: true
                type: LoadBalancer
                loadBalancerIP: 192.168.35.1
                externalTrafficPolicy: Cluster
                annotations:
                    metallb.universe.tf/allow-shared-ip: adguard-home-svc
            dns-udp:
                enabled: true
                type: LoadBalancer
                loadBalancerIP: 192.168.35.1
                externalTrafficPolicy: Cluster
                annotations:
                    metallb.universe.tf/allow-shared-ip: adguard-home-svc
