---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: flux-install
    namespace: flux-system
spec:
    interval: 300m
    path: ./manifests/install
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: flux2
