---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: nfs-subdir-external-provisioner
    namespace: nfs-subdir-external-provisioner
spec:
    interval: 1m
    chart:
        spec:
            chart: nfs-subdir-external-provisioner
            version: 4.0.17
            sourceRef:
                kind: HelmRepository
                name: nfs-subdir-external-provisioner
            interval: 1m
    values:
        nfs:
            server: paradise.local
            path: /srv/nfs

        storageClass:
            create: true
            defaultClass: true
            accessModes: ReadWriteMany
