---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.35.1-192.168.35.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-l2adver
  namespace: metallb-system

